### ISSUE TITLE
Allow certain ouri-definition

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/xst#52]
> Please make sure that the feature you are suggesting is reported in the right place. `Documentation`, `Dashboard` etc all have their own repos. Suggestion for new features should be posted there. 

**Describe the solution you'd like**
I would like to configure the ouri if the exist-context was changed from `/exist` to `/` similar to `-ouri=xmldb:exist://192.168.1.2:80/xmlrpc`

**Describe alternatives you've considered**
n/a

**Additional context**
Changed context for exist from /exist to /

**Comment by line-o** [comment]
I believe there is a setting for that.

**Comment by line-o** [comment]
It's the path in your connection settings see https://github.com/eXist-db/node-exist#defaults

**Comment by line-o** [comment]
@StephanMa If you like this project, please leave a star 😄
