### ISSUE TITLE
Cannot find package 'execa'

### ISSUE THREAD

**Issue by daliboris** [eXist-db/xst#93]
### What happened?

After installing `xst` globally, setting the path to the `npm` repository (`C:\Users\<User>\AppData\Roaming\npm`) and running `xst` from Windows Powershell Command, or a Command Prompt the error `Cannot find package 'execa'` is thrown.

Xst program will not run.

### System Information

```sh
Microsoft Windows [Version 10.0.19045.2604]
```

### Relevant shell output

```sh
PS C:\Users\<User>> xst --version

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'execa' imported from C:\Users\<User>\AppData\Roaming\npm\node_modules\@existdb\xst\commands\edit.js
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by line-o** [comment]
execa is a new dependency introduced with the edit feature.
There might be an issue with this. You could try and install the version before that.

```
npm install -g @existdb/xst@1.5.0
```

Also, I do not really understand what you mean by adding it to npm.

**Comment by daliboris** [comment]
You're right, version 1.5.0 works fine.

I wasn't _adding it to npm_. I just needed to add the path to the `npm` repository to the PATH variable (this information was missing in my report, sorry) on my Windows machine, otherwise running the `xst` command didn't work.

**Comment by line-o** [comment]
@daliboris hmm, it seems that `xst --version` now fails for me too with xst 1.6.0.

**Comment by line-o** [comment]
Thanks for reporting this. The execa dependency was missing in package.json (!)
